name: .NET Core
on:
  push:
    branches: [ main  ]

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Official NuGet Feed settings
  NUGET_FEED: https://api.nuget.org/v3/index.json
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so NerdBank.GitVersioning can do its work

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Restore
        run: dotnet restore ./src

      - name: Build
        run: dotnet build ./src -c Release --no-restore

      - name: Pack
        run: dotnet pack -v minimal -c Release --no-restore --include-symbols --include-source -o nupkg ./src/FFT.Oanda/FFT.Oanda.csproj

      - name: Push to NuGet Feed
        run: dotnet nuget push ./nupkg/*.nupkg --source $NUGET_FEED --skip-duplicate --api-key $NUGET_API_KEY

      - name: Build docfx
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docfx/docfx.json

      - name: Deploy docfx to github pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./docfx/_site
